server {
	listen 80;
	server_name www.example.com;


		root /var/www/html/example;
		index index.htm;

	location / {
		root /var/www/html/example;
		index 1 2 3 4 5 6 7 8 9;
	 }

	location /app {
		index http://localhost:3000;
	 }

	error_page 500 /50x.html;
	location 50x.html {
		root /usr/share/nginx/html;
	}
}

server {
	listen 80;
	server_name www.example.com;

	root /var/www/mtl/;

	location /banana {
		root /var/www/html/example;
		index index.html index.htm;
		return 404;
	 }

	location /app {
		root http://localhost:3000;
	 }

	error_page 500 /500.html;
	error_page 404 /404.html;

	location 50x.html {
		root /usr/share/nginx/html;
	}
}