server { 
	hostname lalala;
	listen 8080;
	interface 9.5.4.1
	;;;;;

;;;
	root /var/www/html/;;;;;;;
	;;
	;
	;
	;
	;
	;
	;
	;



	
	location /app/ {
		index qwer.htm;;;;;;;
	}
}

server {
	hostname banana;;;;;;;;;;;
	;;;;;;;;;;;
	root /banana/bim/;;;;;;;;;
}
