server { 
	hostname lalala;
	listen 8180;
	;;;;;

;;;
	root /var/www/html/;;;;;;;
	;;
	;
	;
	;
	;
	;
	;
	;



	
	location /app/ {
		index qwer.htm;;;;;;;
	}
}

server {
	hostname lalala;;;;;;;;;;;
	;;;;;;;;;;;
	root /banana/bim/;;;;;;;;;
}
