server {
	listen 8000;
	hostname 0.0.0.0;


	root /home/ludebion/Work/WebServ/html/;
	index index.htm index.html;



	location /app/ {
		root /home/ludebion/Work/WebServ/html/;
		index index.html;
		autoindex on;
	 }

	location /uploads/ {
		root /home/ludebion/Work/WebServ/html/uploads/;
		index index.html;
		autoindex off;
	 }

	error_page 404 /404.html;

	client_max_body_size 1717171;
}
