server {
	listen 3600;
	hostname localhost;


	root /home/alpayet/projects/WebServ/www/;
	index index.html;

	location / {
		root /home/alpayet/projects/WebServ/www/;
		index index.html;
		autoindex on;
	 }

	location /app/ {
		root /home/alpayet/projects/WebServ/www/;
		index index.html;
		autoindex on;
	 }

	location /uploads/ {
		root /home/alpayet/projects/WebServ/www/uploads/;
		index index.html;
		autoindex on;
	 }

	location /cgi-bin/ {
        root /home/alpayet/projects/WebServ/www/cgi-bin/;
		cgi broken;
		cgi broken.py;
		cgi cookie.py;
		cgi crash.py;
		cgi delete.sh;
		cgi redirects.py;
		cgi timeout.py;
		cgi upload.py;
    }

	location /508.html/ {
		root /usr/share/nginx/html/;
		limit_except GET;
	}

	client_max_body_size 1000000000000;
}
