server {
	listen 8140;
	interface 10.0.0.0;


	root /var/www/html/example;
	index index.htm;

	location / {
		root /var/www/html/example;
		index banana.html banana.htm;
	 }

	location /app {
		index http://localhost:3000;
	 }

	error_page 500 /50x.html;
	location 50x.html {
		root /usr/share/nginx/html;
	}
}

server {
	listen 9480;
	interface 10.15.2.1;

	root /var/www/mtl/;

	location /banana {
		root /var/www/html/example;
		index index.html index.htm;
		return 404;
	 }

	location /app {
		root http://localhost:3000;
	 }

	error_page 500 /500.html;
	error_page 404 /404.html;

	location 50x.html {
		root /usr/share/nginx/html;
	}
}


server { 
	listen 2000;
	interface 10.0.0.0;
	location bim {

	}
	location boom {

	}
}