server {
	listen 3600;
	hostname localhost;


	root /home/mlouis/projects/milestone05/webserv/www/;
	index index.html;

	# location / {
	# 	root /home/mlouis/projects/milestone05/webserv/www/;
	# 	index indexwioeuqwe index.html;
	# 	autoindex on;
	#  }

	location /app/ {
		root /home/mlouis/projects/milestone05/webserv/www/;
		# index index.tml;
		autoindex off;
	 }

	# location /uploads/ {
	# 	root /home/mlouis/projects/milestone05/webserv/www/uploads/;
	# 	index index.html;
	# 	autoindex on;
	#  }

	location /cgi-bin/ {
        root /home/mlouis/projects/milestone05/webserv/www/cgi-bin/;
		cgi broken;
		cgi broken.py;
		cgi cookie.py;
		cgi crash.py;
		cgi delete.sh;
		cgi redirects.py;
		cgi timeout.py;
		cgi upload.py;
    }

	# location /508.html/ {
	# 	root /usr/share/nginx/html/;
	# 	limit_except GET;
	# }

	client_max_body_size 10000000000;
}
