server {
	listen 8140;
	interface 10.0.0.0;


	root /var/www/html/example/;
	index cacao.htm cacao.html;

	location / {
		root /potato/;
		index banana.html banana.htm;
		autoindex on;
	 }

	location /app/ {
		root /home/alpayet/projects/WebServ/html/;
		index index.html;
		autoindex on;
	 }

	error_page 510 /500.html;
	location /508.html/ {
		root /usr/share/nginx/html/;
		limit_except GET;
	}

	client_max_body_size 1717171;
}