server {
	listen 8030;
	hostname localhost;

	root /home/ludebion/Work/WebServ/html/www/;
	index index.html;

	location / {
		root /home/ludebion/Work/WebServ/html/www/;
		index index.html;
		autoindex on;
	}

	location /cgi-bin/ {
        root /home/ludebion/Work/WebServ/html/www/cgi-bin/;
        cgi cookie.py;
        cgi broken.py;
        cgi crash.py;
        cgi timeout.py;
        cgi upload.py;
        cgi redirects.py;
        cgi delete.sh;
		cgi broken;
	}

	location /uploads/ {
		root /home/ludebion/Work/WebServ/html/www/uploads/;
	 }

	error_page 404 /404.html;

	client_max_body_size 99999999999;
}
