server {
	listen 8000;
	hostname 0.0.0.0;

	root /home/alpayet/projects/WebServ/www/;
	index index.html;

	location / {
		root /home/alpayet/projects/WebServ/www/;
		index index.html;
		autoindex on;
	}

	location /cgi-bin/ {
        root /home/alpayet/projects/WebServ/www/cgi-bin/;
        cgi cookie.py;
        cgi broken.py;
        cgi crash.py;
        cgi timeout.py;
        cgi upload.py;
        cgi redirects.py;
        cgi delete.sh;
        cgi broken;
    }

	location /uploads/ {
		root /home/alpayet/projects/WebServ/www/uploads/;
	 }

	error_page 400 /error.html;
	error_page 403 /error.html;
	error_page 404 /error.html;
	error_page 405 /error.html;
	error_page 408 /error.html;
	error_page 413 /error.html;
	error_page 500 /error.html;
	error_page 501 /error.html;
	error_page 502 /error.html;
	error_page 504 /error.html;

	client_max_body_size 1717171000;
}
