server {
	listen 3600;
	hostname localhost;


	root /home/alpayet/projects/WebServ/www/;
	index index.html;

	# location / {
	# 	root /home/alpayet/projects/WebServ/www/;
	# 	index indexwioeuqwe index.html;
	# 	autoindex on;
	#  }

	location /app/ {
		root /home/alpayet/projects/WebServ/www/;
		# index index.tml;
		autoindex off;
	 }

	# location /uploads/ {
	# 	root /home/alpayet/projects/WebServ/www/uploads/;
	# 	index index.html;
	# 	autoindex on;
	#  }

	# location /cgi-bin/ {
    #     root /home/alpayet/projects/WebServ/www/cgi-bin/;
	# 	cgi broken;
	# 	cgi broken.py;
	# 	cgi cookie.py;
	# 	cgi crash.py;
	# 	cgi delete.sh;
	# 	cgi redirects.py;
	# 	cgi timeout.py;
	# 	cgi upload.py;
    # }

	# location /508.html/ {
	# 	root /usr/share/nginx/html/;
	# 	limit_except GET;
	# }

	client_max_body_size 10000000000;
}

server {
	listen 3600;
	hostname 127.0.0.1;


	root /home/alpayet/projects/WebServ/www/;
	index index.html;

	location / {
		root /home/alpayet/projects/WebServ/www/;
		index index.html;
		autoindex on;
	 }

	location /app/ {
		root /home/alpayet/projects/WebServ/www/;
		index index.html;
		autoindex on;
	 }

	location /uploads/ {
		root /home/alpayet/projects/WebServ/www/uploads/;
		index index.html;
		autoindex on;
	 }

	location /cgi-bin/ {
        root /home/alpayet/projects/WebServ/www/cgi-bin/;
		cgi broken;
		cgi broken.py;
		cgi cookie.py;
		cgi crash.py;
		cgi delete.sh;
		cgi redirects.py;
		cgi timeout.py;
		cgi upload.py;
    }

	location /508.html/ {
		root /usr/share/nginx/html/;
		limit_except GET;
	}

	client_max_body_size 10000;
}
