server {
	listen 8140;
	interface 10.0.0.0;

	hostname banana;
	root /var/www/html/example/;
	index cacao.htm cacao.html;

	location / {
		root /potato/;
		index banana.html banana.htm;
		autoindex on;
	 }

	location /app/ {
		root /bonjour/;
		index index.html;
	 }

	error_page 510 /500.html;
	location /508.html/ {
		root /usr/share/nginx/html/;
		limit_except GET;
	}

	client_max_body_size 1717171;
}

server {
	listen 9480;
	interface 10.15.2.1;

	hostname potato;
	root /var/www/mtl/;

	location /kapouet/ {
		root /mlouis/app/;
		index index.html index.htm;
		return 404;
	 }


	location /app/banana/ {
		root /lol/;
		index index.html index.htm;
		return 404;
	 }

	location /app/ {
		root /potato/;
	 }

	error_page 500 /500.html;
	error_page 404 /404.html;

	location /cgi-bin/ {
		root /usr/share/nginx/html/;
		cgi blabla.py;
		cgi blqwea.py;
		limit_except GET;
	}
}


server { 

	hostname hello;
	listen 2000;
	interface 10.0.0.0;
		root /banana/;
	location /bim/ {
	}
	location /boom/ {

	}
}