server {
	listen 8000;
	hostname 0.0.0.0;


# 	root /home/ludebion/Work/WebServ/html/;
	root /Users/luca/Work/42/Cursus/WebServ/html/;
#	root /workspace/html/;
	index cacao.htm cacao.html;

	location / {
		root /potato/;
		index banana.html banana.htm;
		autoindex on;
	 }

#	location /app/ {
#		root /workspace/html/;
#		index index.html;
#		autoindex on;
#	 }

	location /app/ {
		root /Users/luca/Work/42/Cursus/WebServ/html/;
		index index.html;
		autoindex on;
	 }

# 	location /app/ {
# 		root /home/ludebion/Work/WebServ/html/;
# 		index index.html;
# 		autoindex on;
# 	 }

# 	location /app/ {
# 		root /home/alpayet/projects/WebServ/html/;
# 		index index.html;
# 		autoindex on;
# 	 }

# 	location /app/ {
# 		root /home/marylene/désolé/pitié/excuse_moi/WebServ/html/;
# 		index index.html;
# 		autoindex on;
# 	 }

	error_page 404 /404.html;
	location /508.html/ {
		root /usr/share/nginx/html/;
		limit_except GET;
	}

	client_max_body_size 1717171;
}
