server {
	listen 3600;
	hostname localhost;


	root /home/mlouis/projects/milestone05/webserv/www/;
	index index.html;

	# location / {
	# 	# root /home/mlouis/projects/milestone05/webserv/www/;
	# 	index indexwioeuqwe index.html;
	# 	autoindex on;
	#  }

	location /app/ {
		# root /home/mlouis/projects/milestone05/webserv/www/;
		index index.tml;
		autoindex off;
	 }

	location /nope/ {
		# root /home/mlouis/projects/milestone05/webserv/www/test/;
		# autoindex on;
		return 404;
	 }

	location /cgi-bin/ {
        root /home/mlouis/projects/milestone05/webserv/www/cgi-bin/;
		cgi broken;
		cgi broken.py;
		cgi cookie.py;
		cgi crash.py;
		cgi delete.sh;
		cgi redirects.py;
		cgi timeout.py;
		cgi upload.py;
    }

	error_page 404 /404.html;

	client_max_body_size 10000000000;
}
