server {
	listen 8000;
	hostname 0.0.0.0;

	root /workspace/www/;
	index index.html;

	location / {
		root /workspace/www/;
		index index.html;
		autoindex on;
	}

	location /cgi-bin/ {
        root /workspace/www/cgi-bin/;
        cgi cookie.py;
        cgi broken.py;
        cgi crash.py;
        cgi timeout.py;
        cgi broken;
    }

	client_max_body_size 1717171;
}
