server {
	listen 3030;
	hostname localhost;

	root /Users/luca/Work/42/Cursus/WebServ/www/;
	index index.html;

	location / {
		root /Users/luca/Work/42/Cursus/WebServ/www/;
		index index.html;
		autoindex on;
	}

	location /cgi-bin/ {
        root /Users/luca/Work/42/Cursus/WebServ/www/cgi-bin/;
        cgi cookie.py;
        cgi broken.py;
        cgi crash.py;
        cgi timeout.py;
        cgi upload.py;
        cgi broken;
    }

	location /uploads/ {
		root /Users/luca/Work/42/Cursus/WebServ/www/uploads/;
	 }

	error_page 404 /404.html;

	client_max_body_size 1717171;
}
