server {
	listen 3000;
	hostname localhost;

	root /Users/luca/Work/42/Cursus/WebServ/www/;
	index index.html;

	location / {
		root /Users/luca/Work/42/Cursus/WebServ/www/;
		index index.html;
		autoindex on;
	}

	client_max_body_size 1717171;
}
