#!/usr/bin/env python3
import os
import sys

query = os.environ.get("QUERY_STRING", "")

if "type=local" in query:
    # Local Redirect Response
    sys.stdout.write("Location: /index.html\r\n\r\n")

elif "type=clientdoc" in query:
    # Client Redirect with Document
    sys.stdout.write("Status: 302 Found\r\n")
    sys.stdout.write("Location: http://wikipedia.org\r\n")
    sys.stdout.write("Content-Type: text/html\r\n\r\n")
    sys.stdout.write("<html><body><p>Redirecting...</p></body></html>")

elif "type=client" in query:
    # Client Redirect Response
    sys.stdout.write("Location: https://www.youtube.com/watch?v=qLCRK1SCF88\r\n\r\n")

else:
    # 4. Document Response (Default) — a small on-theme page proving the CGI
    #    rendered a genuinely separate document (reuses the site's stylesheet).
    sys.stdout.write("Content-Type: text/html\r\n\r\n")
    sys.stdout.write("""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>document response — redirects.py</title>
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="/style.css">
</head>
<body>
<div class="wrap">
  <div class="term">
    <div class="term-bar">
      <div class="tl"><span class="r"></span><span class="y"></span><span class="g"></span></div>
      <div class="term-title"><b>response.doc</b> &mdash; redirects.py</div>
    </div>
    <div class="term-body">
      <div class="boot">
        <div class="line"><span class="prompt"></span><span class="verb get">GET</span> <span class="path">/cgi-bin/redirects.py</span><span class="arg">?type=doc</span></div>
        <div class="line"><span class="ok">[ 200 ]</span> <span class="muted">document response &mdash; CGI wrote this straight to stdout</span></div>
      </div>
      <div class="cmd" style="border-top:none;padding-top:0.4rem">
        <div class="cmd-head"><span class="cmd-title">You are on a different page now.</span></div>
        <p class="cmd-desc">This HTML was generated by <code>redirects.py</code> and passed through by webserv unchanged &mdash; the plain <em>Document Response</em> (RFC 3875 &sect;6.2.1), no redirect involved.</p>
        <a class="go" href="/" style="display:inline-block">&larr; back to suite</a>
      </div>
    </div>
  </div>
</div>
</body>
</html>""")
